project:
  type: website
  title: "ISS"
  output-dir: ../_site

website:
  navbar:
    # background: primary
    search: true
    left:
      - text: Course
        file: index.qmd
      - text: Exercises
        file: exercices.qmd
      - text: Presentations
        file: presentations.qmd
    
    # Right side for language selector
    right:
      - text: Language
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: fr/index.html



format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true